version: '3'
services:
  node-api:
    build: .
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - MYSQL_HOST=mysql-db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=mysql 
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      - app-network

  mysql-db:
    container_name: mysql-db
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mysql  
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--user=root", "--password=password"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  mysql-data:

networks:
  app-network:
